services:
  - type: web
    name: dvccc-instagram-manager
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_BASE_URL
        sync: false
      - key: IMGBB_API_KEY
        sync: false
      - key: INSTAGRAM_ACCESS_TOKEN
        sync: false
      - key: INSTAGRAM_ACCOUNT_ID
        sync: false
